### PR TITLE
Onboarding dashboard cache fix

### LINKED ISSUE #406: Incorrect caching of results
When rerunning a step, invalidate cache for results for that step.

### PR DESCRIPTION
**Pull request by pandanautinspace**
Fixes #406 
Add an environment variable switch to bypass GoogleAuth.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/410)

### CODE REVIEW

**Review by Enkidu93 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/410)* status: all files reviewed, 3 unresolved discussions (waiting on @pandanautinspace)

___
*[`onboarding-dashboard/Home.py` line 19 at r1](https://reviewable.io/reviews/sillsdev/silnlp/410#-O-C3nq4BWRXZoiffwmh:-O-C3nq5CvdghUrLmdp5:bukj53g) ([raw file](https://github.com/sillsdev/silnlp/blob/025401f7dac62917c0b24178a62367670a116c57/onboarding-dashboard/Home.py#L19)):*
> ```Python
> 
> disable_g_auth = False
> if os.environ.get("DISABLE_G_AUTH", '').lower() == "true":
> ```

You shouldn't need to interpret is as a string, I don't think. Could be dead wrong. 
___
*[`onboarding-dashboard/Home.py` line 23 at r1](https://reviewable.io/reviews/sillsdev/silnlp/410#-O-C1asXB6TVvXvOkdmZ:-O-C1asXB6TVvXvOkdm_:b-owig7j) ([raw file](https://github.com/sillsdev/silnlp/blob/025401f7dac62917c0b24178a62367670a116c57/onboarding-dashboard/Home.py#L23)):*
> ```Python
> 
> if disable_g_auth:
>     if "set_up" not in st.session_state or st.session_state.set_up == False:
> ```

Instead of boolean == boolean, use `not` as needed.
___
*[`onboarding-dashboard/Home.py` line 24 at r1](https://reviewable.io/reviews/sillsdev/silnlp/410#-O-C44JQ5xIkriZLrgjn:-O-C44JQ5xIkriZLrgjo:b-8cu1hv) ([raw file](https://github.com/sillsdev/silnlp/blob/025401f7dac62917c0b24178a62367670a116c57/onboarding-dashboard/Home.py#L24)):*
> ```Python
> if disable_g_auth:
>     if "set_up" not in st.session_state or st.session_state.set_up == False:
>         st.switch_page("pages/LogInNoGAuth.py")
> ```

I think it might be better to keep one `LogIn` page and disable logic there based on the env var.

**Comment by pandanautinspace** [comment]
Addressed comments in latest commit. 

As far as I can tell, os.environ is a string:string map, so I have to interpret as a string.

**Review by Enkidu93 — COMMENTED** [review]
Oh, yeah, good call. You could just test whether it's set, but I think what you have is fine. 

> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/410#-:-O-CQnHw5g6ZoJQiKkbi:b5ui253)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @pandanautinspace)

**Review by Enkidu93 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/410#-:-O-CR6V65Fp_uqJ4heFY:bg7igkv)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @pandanautinspace)

**Review by pandanautinspace — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/410)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

___
*[`onboarding-dashboard/Home.py` line 19 at r1](https://reviewable.io/reviews/sillsdev/silnlp/410#-O-C3nq4BWRXZoiffwmh:-O-Cg4N4AtD4r_SPcvKF:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/025401f7dac62917c0b24178a62367670a116c57/onboarding-dashboard/Home.py#L19)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

You shouldn't need to interpret is as a string, I don't think. Could be dead wrong.
</blockquote></details>

Done.
___
*[`onboarding-dashboard/Home.py` line 23 at r1](https://reviewable.io/reviews/sillsdev/silnlp/410#-O-C1asXB6TVvXvOkdmZ:-O-CgEW9EbR5fP5d48ko:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/025401f7dac62917c0b24178a62367670a116c57/onboarding-dashboard/Home.py#L23)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Instead of boolean == boolean, use `not` as needed.
</blockquote></details>

Done.
___
*[`onboarding-dashboard/Home.py` line 24 at r1](https://reviewable.io/reviews/sillsdev/silnlp/410#-O-C44JQ5xIkriZLrgjn:-O-CgF-L7XwHXikIvlwk:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/025401f7dac62917c0b24178a62367670a116c57/onboarding-dashboard/Home.py#L24)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I think it might be better to keep one `LogIn` page and disable logic there based on the env var.
</blockquote></details>

Done.

**Review by Enkidu93 — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/410)* status: all files reviewed, 3 unresolved discussions (waiting on @pandanautinspace)

**Pull request merged**
