### PR TITLE
Extend verse counts; unify utilities under 'common' dir

### PR DESCRIPTION
**Pull request by Enkidu93**
Extend collect_verse_counts to collect percentages and chapter-level counts as needed; also unified scripts into common folder (rather than utils folder).

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/313)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
Did you format with Black?

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/313#-:-NpQlAHI9ok5TZ_Z5ex8:blg8vi0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
> Did you format with Black?
> 
> > Reviewed 6 of 6 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/313#-:-NpQlAHI9ok5TZ_Z5ex8:blg8vi0)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

I did not nor did I use isort; when I ran both in the base dir, it changed a lot of files besides the ones I had created, so I wasn't sure if code in silnlp was supposed to use both. Just black maybe but not isort? I can do that.

**Comment by Enkidu93** [comment]
> Did you format with Black?
> 
> > Reviewed 6 of 6 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/313#-:-NpQlAHI9ok5TZ_Z5ex8:blg8vi0)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

Done.

**Review by ddaspit — APPROVED** [review]
We definitely want to use Black. I use isort and mypy as well, but I haven't been as strict on that. I've purposely tried to keep the bar pretty low for committing to silnlp, since there are some non-developers that contribute occasionally.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/313#-:-NpR1kSw4v-4-WgDEHYI:bz2vtvl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
