### PR TITLE
Migrate clowder to silnlp

### PR DESCRIPTION
**Pull request by Enkidu93**
MVP clowder is working smoothly as far as I can tell from my testing. There are still TODOs and other dirty code that will need to be cleaned up moving forward, but moving clowder into silnlp does not involve any changes to other silnlp code, so it ought to be 'safe'. Reviewers: As a result, I don't know if a thorough review is needed at the moment or not. That's your call.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294)

### CODE REVIEW

**Comment by johnml1135** [comment]
*[`clowder/clowder/environment.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniIco90SYJvaf9PdGt:-NniIco90SYJvaf9PdGu:bs9gp22) ([raw file](https://github.com/sillsdev/silnlp/blob/74647ac051616823407413f25f4b605dc488d693/clowder/clowder/environment.py#L52)):*
> ```Python
> 
> 
> class Investigation:
> ```

At least split the investigation class into a separate file.

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Enkidu93)

**Comment by Enkidu93** [comment]
*[`clowder/clowder/environment.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniIco90SYJvaf9PdGt:-NniREEz0KzmC1g_YXBo:b-oxnfsq) ([raw file](https://github.com/sillsdev/silnlp/blob/74647ac051616823407413f25f4b605dc488d693/clowder/clowder/environment.py#L52)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

At least split the investigation class into a separate file.
</blockquote></details>

Can do. I moved it here out of convenience because of circular import issues, but I can fix those.

**Review by johnml1135 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Enkidu93)

___
*[`clowder/clowder/environment.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniIco90SYJvaf9PdGt:-NniRZHcC5Q4ECryPMla:b-tzc8u2) ([raw file](https://github.com/sillsdev/silnlp/blob/74647ac051616823407413f25f4b605dc488d693/clowder/clowder/environment.py#L52)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Can do. I moved it here out of convenience because of circular import issues, but I can fix those.
</blockquote></details>

I would prefer it to be.  Thanks!

**Comment by Enkidu93** [comment]
*[`clowder/clowder/environment.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniIco90SYJvaf9PdGt:-NnijYxz30i9ev4vjxl4:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/74647ac051616823407413f25f4b605dc488d693/clowder/clowder/environment.py#L52)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I would prefer it to be.  Thanks!
</blockquote></details>

Done.

**Review by ddaspit — CHANGES_REQUESTED** [review]
How are dependencies handled in clowder? Will they be handled by poetry? Also, it would be good to format the code using black.

> Reviewed 5 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294#-:-NnirRTd2JrFcP0erHk1:b-cmp96g)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`clowder/gdrive_id_screenshot.png` line 0 at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-Nniphrw2znr4X_S6yC9:-Nniphrw2znr4X_S6yCA:b-1h29q1) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/gdrive_id_screenshot.png#L0)):*
What is the image file for? It is better to avoid checking in binary files.
___
*[`clowder/clowder/clowder` line 1 at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniqCgr1PhTqtUl6xXD:-NniqCgr1PhTqtUl6xXE:b-5k3bam) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/clowder/clowder#L1)):*
> ```
> #! /bin/python
> ```

Does this work on Windows? Many of our users only use Windows.
___
*[`clowder/clowder/environment.py` line 24 at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-NnirFRc2eXtEZL9PxMR:-NnirFRc2eXtEZL9PxMS:b-ch8lq6) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/clowder/environment.py#L24)):*
> ```Python
> from clowder.investigation import Investigation
> from clowder.consts import NAME_ATTRIBUTE, RESULTS_CLEARML_METRIC_ATTRIBUTE, RESULTS_CSVS_ATTRIBUTE, ENTRYPOINT_ATTRIBUTE, GDRIVE_SCOPE
> class MissingConfigurationFile(IOError):
> ```

I think that these classes have been moved to the `investigation.py` file.

**Comment by Enkidu93** [comment]
So in it's own repo, I was using its own poetry. What's the best way to merge those or incorporate both as needed? As for black, done - thank you! - I nearly forgot about that. It was set up to format on save in the other repo, so only the last few changes needed reformatting.

**Comment by Enkidu93** [comment]
*[`clowder/gdrive_id_screenshot.png` line  at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-Nniphrw2znr4X_S6yC9:-NnitD6q4HMzFXHweVP8:b9sfwat) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/gdrive_id_screenshot.png#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is the image file for? It is better to avoid checking in binary files.
</blockquote></details>

It's for the README. It was the clearest way I knew how to point a user to the gdrive id part of the url for a gdrive file/folder. What would you recommend?

**Comment by Enkidu93** [comment]
*[`clowder/clowder/environment.py` line 24 at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-NnirFRc2eXtEZL9PxMR:-NnivznqAfG09VFwFoqQ:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/clowder/environment.py#L24)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think that these classes have been moved to the `investigation.py` file.
</blockquote></details>

Done.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`clowder/clowder/clowder` line 1 at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniqCgr1PhTqtUl6xXD:-Nnj6wS-B8SiGqoqGaQb:b-6y8zb0) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/clowder/clowder#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I will change this to satisfied, so you can get the code into silnlp, but we should create an issue to add support for Windows.
</blockquote></details>

Also, poetry has support for specifying [scripts](https://python-poetry.org/docs/pyproject#scripts) that I believe is cross-platform. It might be a way to solve this issue.

**Comment by Enkidu93** [comment]
*[`clowder/clowder/clowder` line 1 at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniqCgr1PhTqtUl6xXD:-NnjVv5B2YkGfnNPQC4D:b-2v366w) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/clowder/clowder#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Also, poetry has support for specifying [scripts](https://python-poetry.org/docs/pyproject#scripts) that I believe is cross-platform. It might be a way to solve this issue.
</blockquote></details>

Oh, yes! Seems like that should be a simple solution. I noticed, however, when I shadowed Bethany that she used the whole 'python -m ...' rather than the scripts as they're already set up in poetry. Why is that? Is that a compatibility issue or do the scripts not function?

**Comment by johnml1135** [comment]
Has it been formatted with Black?

**Review by johnml1135 — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Comment by Enkidu93** [comment]
Yes, it has. 

Sorry for the delay. Trying to make sure dependencies and poetry setup is right which involved pulling the newest silnlp and the new torch version is taking eons to download. I'll push fixes asap.

**Review by ddaspit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

___
*[`clowder/clowder/clowder` line 1 at r2](https://reviewable.io/reviews/sillsdev/silnlp/294#-NniqCgr1PhTqtUl6xXD:-NnnlhDd2_2qjz1CrHzJ:bdvo6mm) ([raw file](https://github.com/sillsdev/silnlp/blob/efb02a20ff41d20c8aa327d68f1db42820526fc1/clowder/clowder/clowder#L1)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Oh, yes! Seems like that should be a simple solution. I noticed, however, when I shadowed Bethany that she used the whole 'python -m ...' rather than the scripts as they're already set up in poetry. Why is that? Is that a compatibility issue or do the scripts not function?
</blockquote></details>

I just think it is just what they are used to doing.

**Review by johnml1135 — APPROVED** [review]
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/294#-:-Nnp0PE_AIcLC93TXoNb:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
