### PR TITLE
Upgrade eflomal

### LINKED ISSUE #431: Update eflomal to 2.0.0
The pypi eflomal package has yanked all earlier releases and published a new 2.0.0 release, so we need to update the pyproject.yml to use the newest release.

### PR DESCRIPTION
**Pull request by mshannon-sil**
This PR updates eflomal from 0.1 to 2.0.0 to fix #431, modifies the Dockerfile to use the pip installation of eflomal, and adds eflomal to the `ALIGNERS` dictionary in `silnlp/alignment/config.py` permanently instead of only when eflomal is installed so that the error message will be `eflomal is not installed` rather than `invalid aligner`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/433)

### CODE REVIEW

**Review by isaac091 — APPROVED** [review]
:lgtm: 
Can you tag the last commit so that a new image is built and published?

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/433#-:-O0pDqwPDEpa1R3VrRml:b2v2g3d)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Comment by mshannon-sil** [comment]
I removed the change to add eflomal to the `ALIGNERS` dictionary by default, since that's causing experiments to fail when eflomal is not installed, and eflomal is still just an optional requirement.

**Comment by mshannon-sil** [comment]
Merged in Isaac's commit which allows for the updated error message without crashing tasks that don't need eflomal.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/433#-:-O0tXQwm9c_bac8hcWQW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Review by isaac091 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/433#-:-O0t_m9T4USfcxeEgh6G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
