### PR TITLE
Update README.md with conda instructions

### PR DESCRIPTION
**Pull request by mshannon-sil**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/528)

### CODE REVIEW

**Review by isaac091 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/528)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`README.md` line 110 at r1](https://reviewable.io/reviews/sillsdev/silnlp/528#-O7AbEJD44Hax8-km6R-:-O7AbEJD44Hax8-km6R0:bj7ula5) ([raw file](https://github.com/sillsdev/silnlp/blob/46111774f9d7f71c4e9a92c99b4579755d9a05cc/README.md#L110)):*
> ```Markdown
>    ```
> 
> 6. Install [Poetry](https://python-poetry.org/docs/#installing-with-the-official-installer) with the official installer
> ```

Do you need to install a specific version of poetry to match what was used to generate the lock file? I always use the specific version but I don't think I've tried without.

This is just a suggestion, but it might be helpful to write out what steps are actually needed to install, or at least note which steps are required for the basic installation. The instructions are pretty straightforward if you read through all of it but there's a lot of information on that page and it's a bit overwhelming.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/528)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @isaac091)

___
*[`README.md` line 110 at r1](https://reviewable.io/reviews/sillsdev/silnlp/528#-O7AbEJD44Hax8-km6R-:-O7An9t46lm1243TffEK:b-3lirpv) ([raw file](https://github.com/sillsdev/silnlp/blob/46111774f9d7f71c4e9a92c99b4579755d9a05cc/README.md#L110)):*
<details><summary><i>Previously, isaac091 (Isaac Schifferer) wrote…</i></summary><blockquote>

Do you need to install a specific version of poetry to match what was used to generate the lock file? I always use the specific version but I don't think I've tried without.

This is just a suggestion, but it might be helpful to write out what steps are actually needed to install, or at least note which steps are required for the basic installation. The instructions are pretty straightforward if you read through all of it but there's a lot of information on that page and it's a bit overwhelming.
</blockquote></details>

Yes, it should match the lock file version. I just updated the documentation with more detailed steps for installing poetry that also install the correct version.

**Review by isaac091 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/528)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`README.md` line 110 at r1](https://reviewable.io/reviews/sillsdev/silnlp/528#-O7AbEJD44Hax8-km6R-:-O7AtEckDYYNbElk6vVW:b-kl12xk) ([raw file](https://github.com/sillsdev/silnlp/blob/46111774f9d7f71c4e9a92c99b4579755d9a05cc/README.md#L110)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

Yes, it should match the lock file version. I just updated the documentation with more detailed steps for installing poetry that also install the correct version.
</blockquote></details>

Thanks! Do you also have to add poetry to PATH for this setup?

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/528)* status: all files reviewed, 1 unresolved discussion (waiting on @isaac091)

___
*[`README.md` line 110 at r1](https://reviewable.io/reviews/sillsdev/silnlp/528#-O7AbEJD44Hax8-km6R-:-O7Avoc47LmwtGSXowpM:bi90dq6) ([raw file](https://github.com/sillsdev/silnlp/blob/46111774f9d7f71c4e9a92c99b4579755d9a05cc/README.md#L110)):*
<details><summary><i>Previously, isaac091 (Isaac Schifferer) wrote…</i></summary><blockquote>

Thanks! Do you also have to add poetry to PATH for this setup?
</blockquote></details>

No, Poetry by default installs itself in a common directory for the OS it's installed on, which should already be on the user's PATH. I double checked in Linux, and it worked without needing to add anything to PATH like expected.

**Review by isaac091 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/528#-:-O7Ax-vP2_DyTBeBkJSd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`README.md` line 110 at r1](https://reviewable.io/reviews/sillsdev/silnlp/528#-O7AbEJD44Hax8-km6R-:-O7Awv4I36pheeukc93j:b-pzck7e) ([raw file](https://github.com/sillsdev/silnlp/blob/46111774f9d7f71c4e9a92c99b4579755d9a05cc/README.md#L110)):*
<details><summary><i>Previously, mshannon-sil wrote…</i></summary><blockquote>

No, Poetry by default installs itself in a common directory for the OS it's installed on, which should already be on the user's PATH. I double checked in Linux, and it worked without needing to add anything to PATH like expected.
</blockquote></details>

Ok, perfect.

**Review by isaac091 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/528)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
