### PR TITLE
Raise error after all books are translated if any translation failed

### LINKED ISSUE #389: Translate script gives zero exit code on failure
The translate script seems to give a zero exit code even on failure sometimes. See [here](https://app.sil.hosted.allegro.ai/projects/a013a325785b4b34bfb5e69f072c0976/experiments/d27e45b255934df794ff0eb8e8e47a92/info-output/log?columns=selected&columns=type&columns=name&columns=tags&columns=status&columns=project.name&columns=users&columns=started&columns=last_update&columns=last_iteration&columns=parent.name&order=-last_update&filter=). This means that the clearml job will say 'completed' not 'failed' even though it's failed. This makes it difficult for the Onboarding App to distinguish successful and failed jobs.

### PR DESCRIPTION
**Pull request by isaac091**
List failed books in the error message. This doesn't prevent anything else from happening.

Closes #389

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/399)

### CODE REVIEW

**Review by Enkidu93 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/399)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

**Comment by Enkidu93** [comment]
@ddaspit Is there a reason not to make this change? The motivation is that the status-tracking in clowder relies on ClearML task statuses, but for drafting, even if the job fails, it will give a 'completed' status.

**Review by ddaspit — APPROVED** [review]
I'm good with this change.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/399#-:-NzU-Ghw9iA0ZuNgDVRA:bcbf5ft)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Comment by Enkidu93** [comment]
Great! I'm gonna merge it since Isaac is out.

**Pull request merged**
