### PR TITLE
migrate to new silnlp bucket

### PR DESCRIPTION
**Pull request by mshannon-sil**
This PR moves SILNLP from the aqua-ml-data S3 bucket to the new silnlp S3 bucket to address issue #468. I've tested that experiments are able to be successfully run with the new bucket.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/471)

### CODE REVIEW

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/471#-:-O3ITB7SBP2MmqjStYcn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Review by isaac091 — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/471)* status: all files reviewed, 2 unresolved discussions (waiting on @mshannon-sil)

___
*[`silnlp/common/environment.py` line 178 at r1](https://reviewable.io/reviews/sillsdev/silnlp/471#-O3ISEFw4eilbi8fraZV:-O3ISEFw4eilbi8fraZW:bc1224i) ([raw file](https://github.com/sillsdev/silnlp/blob/62b92df5114d868588cde02476012c8a37f5e92f/silnlp/common/environment.py#L178)):*
> ```Python
>         s3 = boto3.resource("s3")
>         data_bucket = s3.Bucket(str(self.data_dir).strip("\\/"))
>         len_aqua_path = len(pt_projects_path)
> ```

Might be good to change this variable name.
___
*[`silnlp/common/environment.py` line 211 at r1](https://reviewable.io/reviews/sillsdev/silnlp/471#-O3ISZG797jOxKdG9z_Y:-O3ISZG797jOxKdG9z_Z:brhumzt) ([raw file](https://github.com/sillsdev/silnlp/blob/62b92df5114d868588cde02476012c8a37f5e92f/silnlp/common/environment.py#L211)):*
> ```Python
>         s3 = boto3.resource("s3")
>         data_bucket = s3.Bucket(str(self.data_dir).strip("\\/"))
>         len_aqua_path = len(experiments_path)
> ```

Same here.

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/471)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @isaac091)

___
*[`silnlp/common/environment.py` line 178 at r1](https://reviewable.io/reviews/sillsdev/silnlp/471#-O3ISEFw4eilbi8fraZV:-O3JRYCL3KLY8wLyAQWy:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/62b92df5114d868588cde02476012c8a37f5e92f/silnlp/common/environment.py#L178)):*
<details><summary><i>Previously, isaac091 (Isaac Schifferer) wrote…</i></summary><blockquote>

Might be good to change this variable name.
</blockquote></details>

Done.
___
*[`silnlp/common/environment.py` line 211 at r1](https://reviewable.io/reviews/sillsdev/silnlp/471#-O3ISZG797jOxKdG9z_Y:-O3JRYsk36Mz_a6Wq9-5:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/62b92df5114d868588cde02476012c8a37f5e92f/silnlp/common/environment.py#L211)):*
<details><summary><i>Previously, isaac091 (Isaac Schifferer) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.

**Review by isaac091 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/471#-:-O3JSN9m0RnAbIydaMDF:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mshannon-sil)

**Review by isaac091 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/471)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
