### PR TITLE
Single execution

### PR DESCRIPTION
**Pull request by johnml1135**
This should be ready to a single command execution in ClearML.
* There are some instructions on setting up the SSH, Google Drive  and ClearML creds.
* It only uses AQUA data
* It is ready to try out on a GPU for a real experiment.

### CODE REVIEW

**Comment by johnml1135** [comment]
@ddaspit,  can you review this?

**Review by ddaspit — APPROVED** [review]

**Comment by johnml1135** [comment]
I want to do the folder structure before move.
Project/experiment/*.yaml

**Comment by johnml1135** [comment]
And write basic instructions for creating a experiment and cloning it.

**Comment by johnml1135** [comment]
There may be still more to do. but we can merge this now.

**Pull request merged**
