### PR TITLE
add script to remove >3 month old model files

### PR DESCRIPTION
**Pull request by mshannon-sil**
Added a script to remove any model files that haven't been modified in over 3 months. I approximated a month in terms of the average number of seconds in a month to keep the calculation simple. It's not exact, but I figure it will do for our purposes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/369)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/369)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`scripts/clean_s3.py` line 9 at r1](https://reviewable.io/reviews/sillsdev/silnlp/369#-NwBFGPyA5RlvujBs5tz:-NwBFGPyA5RlvujBs5u-:bwyefda) ([raw file](https://github.com/sillsdev/silnlp/blob/177f596a591a188e1198ae943a672f8470ebf67a/scripts/clean_s3.py#L9)):*
> ```Python
> 
> 
> def main() -> None:
> ```

It would probably be good to add a `--dry-run` command-line option that does not actually delete the files, but still reports how many files would have been deleted.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/369#-:-NwFc-KwCFKhSjPu3Ip6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Review by ddaspit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/369)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`scripts/clean_s3.py` line 11 at r2](https://reviewable.io/reviews/sillsdev/silnlp/369#-NwFc429-0OsIEE-20mG:-NwFc429-0OsIEE-20mH:b-yw1lej) ([raw file](https://github.com/sillsdev/silnlp/blob/e323bbca0ab5d3ab4b5618c53dbac5ecbe4ae5a4/scripts/clean_s3.py#L11)):*
> ```Python
> 
> def clean_s3(dry_run: bool) -> None:
>     max_age = 2 * MONTH_IN_SECONDS
> ```

Did you purposefully change it to two months?

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/369)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`scripts/clean_s3.py` line 11 at r2](https://reviewable.io/reviews/sillsdev/silnlp/369#-NwFc429-0OsIEE-20mG:-NwFeKLn1T5px2ITu40w:b-jsbkcr) ([raw file](https://github.com/sillsdev/silnlp/blob/e323bbca0ab5d3ab4b5618c53dbac5ecbe4ae5a4/scripts/clean_s3.py#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Did you purposefully change it to two months?
</blockquote></details>

That's a hold over from testing I was doing for the dry-run option, changed it back to three months.

**Review by ddaspit — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/369)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
