### PR TITLE
Provide ability to override silnlp pt dir, scripture dir, and terms dir via env vars

### PR DESCRIPTION
**Pull request by Enkidu93**
Necessary for https://github.com/sillsdev/silnlp/issues/310

I'll push all of the necessary clowder changes to main once this is merged.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/335)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/335)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @mshannon-sil)

___
*[`silnlp/common/environment.py` line 48 at r1](https://reviewable.io/reviews/sillsdev/silnlp/335#-Nrb93w715zzGN6i-T2L:-Nrb93w81YLToI_tL-1r:b-hy6en4) ([raw file](https://github.com/sillsdev/silnlp/blob/46a59ee4a557721aa5d586aca12ef188858bfabf/silnlp/common/environment.py#L48)):*
> ```Python
>         elif os.getenv("SIL_NLP_PT_DIR"):
>             self.pt_dir = self.data_dir / os.getenv("SIL_NLP_PT_DIR", "")
>         elif os.getenv("OVERRIDE_FULL_SIL_NLP_PT_DIR"):
> ```

What is the difference between `SIL_NLP_PT_DIR` and `OVERRIDE_FULL_SIL_NLP_PT_DIR`?
___
*[`silnlp/common/environment.py` line 86 at r1](https://reviewable.io/reviews/sillsdev/silnlp/335#-Nrb9Y7z6FV8RdQvniMc:-Nrb9Y7z6FV8RdQvniMd:b-80odz1) ([raw file](https://github.com/sillsdev/silnlp/blob/46a59ee4a557721aa5d586aca12ef188858bfabf/silnlp/common/environment.py#L86)):*
> ```Python
>             self.mt_dir = self.data_dir / "MT"
>         self.mt_corpora_dir = self.mt_dir / "corpora"
>         if os.getenv("OVERRIDE_FULL_SIL_NLP_TERMS_DIR"):
> ```

I would rename this to `SIL_NLP_MT_TERMS_DIR`.
___
*[`silnlp/common/environment.py` line 90 at r1](https://reviewable.io/reviews/sillsdev/silnlp/335#-Nrb9fGH1RXGnNHcUvUk:-Nrb9fGH1RXGnNHcUvUl:bh2iayh) ([raw file](https://github.com/sillsdev/silnlp/blob/46a59ee4a557721aa5d586aca12ef188858bfabf/silnlp/common/environment.py#L90)):*
> ```Python
>         else:
>             self.mt_terms_dir = self.mt_dir / "terms"
>         if os.getenv("OVERRIDE_FULL_SIL_NLP_SCRIPTURE_DIR"):
> ```

I would rename this to `SIL_NLP_MT_SCRIPTURE_DIR`.

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/335)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @mshannon-sil)

___
*[`silnlp/common/environment.py` line 48 at r1](https://reviewable.io/reviews/sillsdev/silnlp/335#-Nrb93w715zzGN6i-T2L:-NrbCMd61YukaGDMi_9D:br92eiw) ([raw file](https://github.com/sillsdev/silnlp/blob/46a59ee4a557721aa5d586aca12ef188858bfabf/silnlp/common/environment.py#L48)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is the difference between `SIL_NLP_PT_DIR` and `OVERRIDE_FULL_SIL_NLP_PT_DIR`?
</blockquote></details>

Nothing
___
*[`silnlp/common/environment.py` line 86 at r1](https://reviewable.io/reviews/sillsdev/silnlp/335#-Nrb9Y7z6FV8RdQvniMc:-NrbCQ2mCgWoBbTppwTu:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/46a59ee4a557721aa5d586aca12ef188858bfabf/silnlp/common/environment.py#L86)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `SIL_NLP_MT_TERMS_DIR`.
</blockquote></details>

Done.
___
*[`silnlp/common/environment.py` line 90 at r1](https://reviewable.io/reviews/sillsdev/silnlp/335#-Nrb9fGH1RXGnNHcUvUk:-NrbCPOl2jK1Rs0y1l1m:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/46a59ee4a557721aa5d586aca12ef188858bfabf/silnlp/common/environment.py#L90)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `SIL_NLP_MT_SCRIPTURE_DIR`.
</blockquote></details>

Done.

**Review by mshannon-sil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/335#-:-NrfGSZI9-0mP62b864V:bnfp4nl)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ddaspit)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/335#-:-NrfacNsBo5aUaD9hqMp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

**Pull request merged**
