### PR TITLE
Update setup documentation and Docker images

### PR DESCRIPTION
**Pull request by isaac091**
Main changes

Docker images:
* Remove AWS CLI install from dev container
* Make separate silnlp caches for experiments and projects

README:
* Replaced manual setup process with dev container setup process
* Moved S3 bucket setup instructions to a separate file and consolidated ClearML setup instructions.
* Removed Pycharm setup instructions

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/380)

### CODE REVIEW

**Review by mshannon-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/380)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @isaac091)

___
*[`Dockerfile` line 117 at r1](https://reviewable.io/reviews/sillsdev/silnlp/380#-NxXkKyu788XOqkh1sAW:-NxXkKyu788XOqkh1sAX:b-fz2znb) ([raw file](https://github.com/sillsdev/silnlp/blob/bec0ade8c5e05075ec5f2d3c8ec3fd9f948bf04e/Dockerfile#L117)):*
> ```Dockerfile
> ENV SIL_NLP_DATA_PATH=/aqua-ml-data
> ENV CLEARML_API_HOST="https://api.sil.hosted.allegro.ai"
> ENV AWS_REGION="us-east-1"
> ```

I'm not sure we should set the AWS_REGION in the published dockerfile. If the user has an S3 bucket, they might want to use a different region.
___
*[`manual_setup.md` line 4 at r1](https://reviewable.io/reviews/sillsdev/silnlp/380#-NxXljMs3QA4cMq74l11:-NxXljMs3QA4cMq74l12:bzcl8wu) ([raw file](https://github.com/sillsdev/silnlp/blob/bec0ade8c5e05075ec5f2d3c8ec3fd9f948bf04e/manual_setup.md#L4)):*
> ```Markdown
> 
> ## SILNLP Prerequisites
> These are the main requirements for the SILNLP code to run on a local machine. The SILNLP repo itself is hosted on Github, mainly written in Python and calls SIL.Machine.Tool. 'Machine' as we tend to call it, is a .NET application that has many functions for manipulating USFM data. Most of the language data we have for low resource languages in USFM format. Since Machine is a .Net application it depends upon the __.NET core SDK__ which works on Windows and Linux. Since there are many python packages that need to be used, with complex versioning requirements we use a Python package called Poetry to mangage all of those. So here is a rough heirarchy of SILNLP with the major dependencies.
> ```

May as well fix some grammatical issues that were there before.
"Most of the language data we have for low resource languages is in USFM format" (inserted "is"). 
"Since there are many Python packages that need to be used, with complex versioning requirements, we use a Python package ..." (capitalized Python, added a comma)
___
*[`manual_setup.md` line 54 at r1](https://reviewable.io/reviews/sillsdev/silnlp/380#-NxXnGQg3IgR4fRnX2Or:-NxXnGQg3IgR4fRnX2Os:b-yzqxae) ([raw file](https://github.com/sillsdev/silnlp/blob/bec0ade8c5e05075ec5f2d3c8ec3fd9f948bf04e/manual_setup.md#L54)):*
> ```Markdown
>       ```
> 5. .NET Core SDK
>    * The necessary versions are 7.0 and 3.1. If your machine is only able to install version 7.0, you can set the DOTNET_ROLL_FORWARD environment variable to "LatestMajor", which will allow you to run anything that depends on dotnet 3.1.
> ```

Machine has been upgraded to use dotnet 8.0 since this was written, so we should update that here as well as in the dockerfiles.
___
*[`README.md` line 13 at r1](https://reviewable.io/reviews/sillsdev/silnlp/380#-NxXo3v3AMnnnAjUCuaN:-NxXo3v3AMnnnAjUCuaO:b7hca31) ([raw file](https://github.com/sillsdev/silnlp/blob/bec0ade8c5e05075ec5f2d3c8ec3fd9f948bf04e/README.md#L13)):*
> ```Markdown
> 
> ## SILNLP Prerequisites
> These are the main requirements for the SILNLP code to run on a local machine. The SILNLP repo itself is hosted on Github, mainly written in Python and calls SIL.Machine.Tool. 'Machine' as we tend to call it, is a .NET application that has many functions for manipulating USFM data. Most of the language data we have for low resource languages in USFM format. Since Machine is a .Net application it depends upon the __.NET core SDK__ which works on Windows and Linux. Since there are many python packages that need to be used, with complex versioning requirements we use a Python package called Poetry to mangage all of those. So here is a rough heirarchy of SILNLP with the major dependencies.
> ```

Same grammar fixes as in manual_setup.md.
"Most of the language data we have for low resource languages is in USFM format" (inserted "is"). 
"Since there are many Python packages that need to be used, with complex versioning requirements, we use a Python package ..." (capitalized Python, added a comma)
___
*[`.devcontainer/Dockerfile` line 55 at r1](https://reviewable.io/reviews/sillsdev/silnlp/380#-NxXpxic75I0oWaehxBi:-NxXpxic75I0oWaehxBj:b-k1vgoy) ([raw file](https://github.com/sillsdev/silnlp/blob/bec0ade8c5e05075ec5f2d3c8ec3fd9f948bf04e/.devcontainer/Dockerfile#L55)):*
> ```Dockerfile
> ENV CLEARML_API_HOST="https://api.sil.hosted.allegro.ai"
> ENV SIL_NLP_DATA_PATH=/aqua-ml-data
> ENV AWS_REGION="us-east-1"
> ```

Same question as earlier about whether we should include AWS_REGION.

**Comment by isaac091** [comment]
> Machine has been upgraded to use dotnet 8.0 since this was written, so we should update that here as well as in the dockerfiles.

Do we still need the DOTNET_ROLL_FORWARD environment variable with the upgrade?

**Review by mshannon-sil — COMMENTED** [review]
Good question, I'm not sure. It depends on whether all the dotnet dependencies were upgraded to 8.0, or whether just the dotnet 7.0 dependencies were upgraded. I should be able to check by running some SMT experiments without DOTNET_ROLL_FORWARD.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/380#-:-NxYD9w6-T_v9s_X26Rc:b-6n7xf8)* status: 0 of 8 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @isaac091)

**Review by ddaspit — COMMENTED** [review]
The only thing that .NET is used for is to run the .NET versions of the Machine alignment models. Really, I'm the only one that would want to do that. I'm fine with removing the requirement for .NET from the documentation. We could just have one sentence that mentions that you need to install .NET if you want to run the .NET Machine alignment models.

> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/380#-:-NxYO7hODomM7FRFJTcW:bvtlrbh)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @isaac091 and @mshannon-sil)

**Comment by isaac091** [comment]
> I'm not sure we should set the AWS_REGION in the published dockerfile. If the user has an S3 bucket, they might want to use a different region.

If we're going to take this out, would it make sense to also have the user set CLEARML_API_HOST and SIL_NLP_DATA_PATH?

**Review by mshannon-sil — COMMENTED** [review]
If .NET isn't needed then removing the dependency makes sense with that note to install it if you need the .NET Machine alignment models. I also tried running a bunch of different scripts without DOTNET_ROLL_FORWARD, and I didn't encounter any issues.

For those other two env variables, I think they can be removed from the user-oriented docker container, but left in the dev container to keep it simpler for the team.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/380#-:-NxYyVD7D2oKKrFvuNuD:b-t4er7n)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @isaac091)

**Comment by isaac091** [comment]
I also added a couple changes to `devcontainer.json` based on issues Laura ran into while getting set up with the dev container:
* Replaced `/home` with `${env:HOME}` in volume mounting to be OS-agnostic
* Added note in setup instructions about commenting out `--gpus all` if you don't have a local GPU. I couldn't find a way to conditionally use that option, and there's no option to only use a GPU if you have one, so the solution is a workaround for now.

**Review by mshannon-sil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/380#-:-NxmTckdCXeMFcZ9ykoK:bnfp4nl)* status: 2 of 8 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @isaac091)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/380#-:-NxnKTysE7QsFlVKOJMR:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @isaac091)

**Pull request merged**
