### PR TITLE
Use silnlp image, use system-site-packages

### PR DESCRIPTION
**Pull request by mshannon-sil**
This PR replaces the old nvidia/cuda image in `clearml_connection.py` with the SILNLP docker image. There are additions to the `docker_setup_bash_script` to allow Poetry to use system-site-packages. It now only takes ~6 seconds instead of ~1 minute for all the packages to be installed when running an experiment.

You'll see that it currently specifies an exact version of the SILNLP docker container rather than using `latest`. This is because currently the ClearML agents are set to not pull new versions of docker images, so `latest` doesn't work. If we'd like the ClearML agents to always check for the latest version of the SILNLP image, I can update that in the `clearml.conf`. And then once all the agents are restarted I can update this code.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/542)

### CODE REVIEW

**Comment by TaperChipmunk32** [comment]
Could you take a look at my most recent ClearML task? When I tried to test this branch, the experiment seems to be stuck on downloading the full Docker image. Part of it seems to have been successfully downloaded, but it is not continuing to either another download or the actual task.

**Comment by mshannon-sil** [comment]
I'm rerunning your task, and I'm going to try giving it an extra long time and see if that helps it download the image.

**Comment by mshannon-sil** [comment]
@TaperChipmunk32 I ran a full test on the AQuA server verifying the image works there. Can you confirm also that you're able to run jobs with this branch now?

**Comment by TaperChipmunk32** [comment]
> @TaperChipmunk32 I ran a full test on the AQuA server verifying the image works there. Can you confirm also that you're able to run jobs with this branch now?

I was able to successfully run a job on the AQuA server using the branch.

**Review by TaperChipmunk32 — APPROVED** [review]

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/542)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`silnlp/nmt/clearml_connection.py` line 60 at r1](https://reviewable.io/reviews/sillsdev/silnlp/542#-O8D1ddC3WygbJOkVx_E:-O8D1ddD-EmK9j4pqNfs:b-mb7erw) ([raw file](https://github.com/sillsdev/silnlp/blob/9e0da30169d95bbadb2e545b1071ec12216272ba/silnlp/nmt/clearml_connection.py#L60)):*
> ```Python
>                     "PATH=$PATH:/root/.local/bin",
>                     "pipx install poetry==1.7.1",
>                     "poetry config virtualenvs.options.system-site-packages true",
> ```

Can you put a comment here explaining what this does?

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/542)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`silnlp/nmt/clearml_connection.py` line 60 at r1](https://reviewable.io/reviews/sillsdev/silnlp/542#-O8D1ddC3WygbJOkVx_E:-O8DsjsJ7DSDC7EhYXjd:b-896fix) ([raw file](https://github.com/sillsdev/silnlp/blob/9e0da30169d95bbadb2e545b1071ec12216272ba/silnlp/nmt/clearml_connection.py#L60)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Can you put a comment here explaining what this does?
</blockquote></details>

Done.

**Comment by mshannon-sil** [comment]
I've also gone ahead and updated the clearml.conf files for the AQuA/Cheetah servers to always try pulling the docker image. There are currently discussions on doing maintenance on the servers relatively soon, at which point the agents will be restarted and the changes will take effect. Once that happens, I'll change this PR to use `silnlp:latest` rather than a specific version of the image, so let's hold off on merging the PR for now.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/542#-:-O8E-Cg38ma0H3O3NCui:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
