### PR TITLE
Added an option for a book filter for KBTs

### PR DESCRIPTION
**Pull request by TaperChipmunk32**
-In the config file, under the terms section, a new option was added: filter_books.
-filter_books uses the same syntax as corpus_books, except chapter selections will be ignored.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/531)

### CODE REVIEW

**Comment by TaperChipmunk32** [comment]
Once this is merged, I will also update the Wiki to include the filter_books config option.

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/531)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil and @TaperChipmunk32)

___
*[`silnlp/nmt/config.py` line 1040 at r1](https://reviewable.io/reviews/sillsdev/silnlp/531#-O7a2amH4ii1Nn6UVbeJ:-O7a2amH4ii1Nn6UVbeK:b-srm1h8) ([raw file](https://github.com/sillsdev/silnlp/blob/ad1aacfed614f9cd84b98947a14b02ee170bf561/silnlp/nmt/config.py#L1040)):*
> ```Python
> 
>         try:
>             filter_books = get_chapters(self.data["terms"]["filter_books"]).keys()
> ```

You should use the `get_books` function instead.

**Comment by TaperChipmunk32** [comment]
I chose to use get_chapters, since it allows for book ranges (1JN-3JN), while get_books does not. However, I think I'll just add that to get_books to make them consistent.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/531#-:-O7oBDHcD_dIzZ_z6QjV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
