### PR TITLE
Experiment translate option

### PR DESCRIPTION
**Pull request by isaac091**
Adds --translate option for experiments. Users can define a list translate configs in the config file using the same arguments as the translate script.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/325)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/325)* status: all files reviewed, 1 unresolved discussion (waiting on @isaac091)

___
*[`silnlp/nmt/experiment.py` line 87 at r1](https://reviewable.io/reviews/sillsdev/silnlp/325#-Nr0jyC7CoRqd7yCp6bC:-Nr0jyC8AlPcFBCdJWR_:b11p6mj) ([raw file](https://github.com/sillsdev/silnlp/blob/c0c7b7619a517c3047e6050add18fa59d19db458/silnlp/nmt/experiment.py#L87)):*
> ```Python
> 
>     def translate(self):
>         translate_configs = self.config.translate
> ```

What about the possibility of having the experiment script accept the same CLI arguments as the translate script? I don't love specifying the translate arguments in the experiment config.

**Comment by mmartin9684-sil** [comment]
It's not unusual to need to use the same model to create several draft translations - e.g., from English Bible A to the vernacular, and from English Bible B to the vernacular.

If we want to go with command line arguments for the translate step, would it be possible to support this?

**Comment by isaac091** [comment]
I think having a separate `translate_config.yml` like we talked about this morning makes the most sense. This way it's completely separated from the training and we're still able to have multiple translation requests in one go.

**Review by ddaspit — APPROVED** [review]
I like it.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/325#-:-Nr6OF316w11FYLO0y2X:b8eau52)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Pull request merged**
