### PR TITLE
Issue 333: Fixed bug with dupe key terms during preprocessing

### PR DESCRIPTION
**Pull request by TaperChipmunk32**
-Key Terms are no longer collected per corpus pair, done once for the whole corpus
-Any remaining duplicates are removed (repeated proper names)

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503)* status: all files reviewed, 2 unresolved discussions (waiting on @mshannon-sil and @TaperChipmunk32)

___
*[`silnlp/nmt/config.py` line 537 at r1](https://reviewable.io/reviews/sillsdev/silnlp/503#-O5to9-32yoU-whSga9z:-O5to9-32yoU-whSgaA-:b-5anz6y) ([raw file](https://github.com/sillsdev/silnlp/blob/6dfe3f555ff6143faea47c91252f12695f9e2f44/silnlp/nmt/config.py#L537)):*
> ```Python
>         train_count = 0
>         terms_config = self.data["terms"]
>         src_terms_files: Dict[DataFile, str] = {}
> ```

We don't need to use a dict here. We can just use a list of tuples.
___
*[`silnlp/nmt/config.py` line 1041 at r1](https://reviewable.io/reviews/sillsdev/silnlp/503#-O5tnJZT9_M1pwsz8_Ec:-O5tnJZT9_M1pwsz8_Ed:b-3lqegp) ([raw file](https://github.com/sillsdev/silnlp/blob/6dfe3f555ff6143faea47c91252f12695f9e2f44/silnlp/nmt/config.py#L1041)):*
> ```Python
>     def _write_terms(self, tokenizer: Tokenizer, src_terms_files: Dict[DataFile, str], trg_terms_files: Dict[DataFile, str]) -> int:
>         terms = self._collect_terms(src_terms_files, trg_terms_files)
>         terms = terms.drop_duplicates(subset=["source"])
> ```

This will drop all rows that have duplicate source terms and all rows that have duplicate target terms. I don't think that is what we want. We want to drop all rows that have duplicate source and target terms. We want this:
``` py
terms = terms.drop_duplicates(subset=["source", "target"])
```

**Review by mshannon-sil — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @TaperChipmunk32)

___
*[`silnlp/nmt/config.py` line 90 at r1](https://reviewable.io/reviews/sillsdev/silnlp/503#-O5uEm5b4jttozz8cwYN:-O5uEm5b4jttozz8cwYO:bwjw094) ([raw file](https://github.com/sillsdev/silnlp/blob/6dfe3f555ff6143faea47c91252f12695f9e2f44/silnlp/nmt/config.py#L90)):*
> ```Python
>         )
>     
>     def __hash__(self) -> int:
> ```

Based on Damien's comment, you can remove the hash method if you don't need to use a dict.
___
*[`silnlp/nmt/config.py` line 1041 at r1](https://reviewable.io/reviews/sillsdev/silnlp/503#-O5tnJZT9_M1pwsz8_Ec:-O5uBo__D_Q-gNjaHjb8:buovomv) ([raw file](https://github.com/sillsdev/silnlp/blob/6dfe3f555ff6143faea47c91252f12695f9e2f44/silnlp/nmt/config.py#L1041)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This will drop all rows that have duplicate source terms and all rows that have duplicate target terms. I don't think that is what we want. We want to drop all rows that have duplicate source and target terms. We want this:
``` py
terms = terms.drop_duplicates(subset=["source", "target"])
```
</blockquote></details>

From the meeting I understood the consensus to be dropping rows that had duplicate source terms even if they had duplicate target terms, and vice versa. I agree that's not what we want, because that's information we would want to give the model.

These statements using the `terms` variable should also be moved after the `if terms is None:` check.

**Comment by TaperChipmunk32** [comment]
Thank you both for the feedback. I just pushed a new commit that addresses the changes requested.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503)* status: all files reviewed, 2 unresolved discussions (waiting on @mshannon-sil and @TaperChipmunk32)

___
*[`silnlp/nmt/hugging_face_config.py` line 627 at r3](https://reviewable.io/reviews/sillsdev/silnlp/503#-O62sAHm5K7f3Z6tv7Mk:-O62sAHm5K7f3Z6tv7Ml:b28o6zw) ([raw file](https://github.com/sillsdev/silnlp/blob/2bb7aced27e8596694b8546aa71eba8cf34417a4/silnlp/nmt/hugging_face_config.py#L627)):*
> ```Python
> 
>             all_trg_terms: List[Tuple[DataFile, Dict[str, Term], str]] = []
>             for trg_terms_file in trg_terms_files:
> ```

It would probably be cleaner to destructure the tuple in the `for` loop.

**Review by mshannon-sil — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503)* status: all files reviewed, 1 unresolved discussion (waiting on @TaperChipmunk32)

**Review by mshannon-sil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503#-:-O62xA9u3nbX2ioXzBPq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @TaperChipmunk32)

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503#-:-O635CYQC3AfgeJnNsdw:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TaperChipmunk32)

**Review by ddaspit — COMMENTED** [review]
Good job on your first PR.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/503#-:-O635Dlx0rqnjeK9rW5p:bm0mgnj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TaperChipmunk32)

**Pull request merged**
