### PR TITLE
Make eflomal an optional dependency

### PR DESCRIPTION
**Pull request by isaac091**
Made eflomal an "extra" in the poetry config. The update also removed the "category" attribute from all of the packages in the lock file and it seems like this is because I was using a newer version of Poetry (1.6.1). I can redo with a different version if necessary.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/203)

### CODE REVIEW

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/203)* status: all files reviewed, 1 unresolved discussion (waiting on @isaac091)

___
*[`pyproject.toml` line 79 at r1](https://reviewable.io/reviews/sillsdev/silnlp/203#-NgPjhtKDApe4DINcllq:-NgPjhtKDApe4DINcllr:bcajn7s) ([raw file](https://github.com/sillsdev/silnlp/blob/7207b6dc0572e2a5dd5bf6f5c6a0f5f90fbb3105/pyproject.toml#L79)):*
> ```TOML
> python-docx = "^0.8.11"
> iso639-lang = "^2.1.0"
> eflomal = { version = "^0.1", optional = true }
> ```

I just want to make sure that this works how I would expect. If you run `poetry install`, the eflomal dependency will not be installed. If you run `poetry install -E eflomal`, then eflomal will be installed. Is that correct?

**Comment by isaac091** [comment]
That's correct. I just verified on my system.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/203#-:-NgPwUIp93aCuTVJDKBJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Pull request merged**
