### PR TITLE
Fix for #540, issues (+ support for multiple translations) with exper…

### PR DESCRIPTION
**Pull request by benjaminking**
This is a fix for #540, the brackets issue that Matthew found.  It was caused by a mismatch in types between the output from Huggingface's pipeline and the Python typing hints when passing tokenized inputs to the pipeline. (The types are correct when it is given untokenized inputs)  This mismatch only shows up when running `python -m silnlp.nmt.experiment --test`.

This commit fixes that issue by restructuring the output format in the case of tokenized inputs to be identical to the untokenized case.  It also adds support for multiple translations when running `python -m silnlp.nmt.experiment --test`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/544)

### CODE REVIEW

**Review by ddaspit — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/544)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminking)

___
*[`silnlp/nmt/hugging_face_config.py` line 1067 at r1](https://reviewable.io/reviews/sillsdev/silnlp/544#-O8E-hnG9uO4fi4RsBwg:-O8E-hnHDj8_ix2ARalr:b-kawnmu) ([raw file](https://github.com/sillsdev/silnlp/blob/11e5baae89b212a9c4b60dcb6cd3bdcaae30ee90/silnlp/nmt/hugging_face_config.py#L1067)):*
> ```Python
> 
>     def get_num_drafts(self) -> int:
>         num_drafts = self._config.infer.get("num_drafts")
> ```

I believe that `get` could return `None` if `num_drafts` isn't set. You might want to switch this to `self._config.infer["num_drafts"]`. Or you could return a default value `get("num_drafts", 1)`.
___
*[`silnlp/nmt/test.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/silnlp/544#-O8E0FR160wlJ5Oku01Y:-O8E0FR160wlJ5Oku01Z:b-b95x0q) ([raw file](https://github.com/sillsdev/silnlp/blob/11e5baae89b212a9c4b60dcb6cd3bdcaae30ee90/silnlp/nmt/test.py#L52)):*
> ```Python
>     def writeHeader(self, file: IO) -> None:
>         header = (
>             "book,draft_index,src_iso,trg_iso,num_refs,references,sent_len"
> ```

@Enkidu93 Will this break any other tools that read this file, such as the onboarding tool?

**Comment by benjaminking** [comment]
I've added a fix for the first issue.

For the second, it would be possible to leave the output format unchanged in the case when the user doesn't include `--multiple-translations`, but I had initially decided against it, since I wasn't sure if having two different output formats would be a good choice either.

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/544)* status: all files reviewed, 1 unresolved discussion (waiting on @benjaminking)

**Review by Enkidu93 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/544)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`silnlp/nmt/test.py` line 52 at r1](https://reviewable.io/reviews/sillsdev/silnlp/544#-O8E0FR160wlJ5Oku01Y:-O8HzKNq-Zb1nkzfhwqo:b-j4ulxr) ([raw file](https://github.com/sillsdev/silnlp/blob/11e5baae89b212a9c4b60dcb6cd3bdcaae30ee90/silnlp/nmt/test.py#L52)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

@Enkidu93 Will this break any other tools that read this file, such as the onboarding tool?
</blockquote></details>

No, this should be a safe change to make.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/544#-:-O8I-Il48EMISng51LUm:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @benjaminking)

**Pull request merged**
