### PR TITLE
add conda environment.yml for non-python-package dependencies

### PR DESCRIPTION
**Pull request by mshannon-sil**
This PR adds an environment.yml file so that conda can be used as another option besides docker. Once the PR is approved, I'll also update the wiki to document how to run SILNLP with conda and how to set up a clearml-agent using conda.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/524)

### CODE REVIEW

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/524#-:-O766eZHEUL1v0QMynii:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @isaac091)

**Review by isaac091 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/524)* status: all files reviewed, 1 unresolved discussion (waiting on @mshannon-sil)

___
*[`environment.yml` line 6 at r1](https://reviewable.io/reviews/sillsdev/silnlp/524#-O768xcF80EgYlmkhE6M:-O768xcF80EgYlmkhE6N:bbq01sg) ([raw file](https://github.com/sillsdev/silnlp/blob/1866015f1725d81d050ace5cb18c2efaa39d14d2/environment.yml#L6)):*
> ```YAML
>   - conda-forge
> dependencies:
>   - python>=3.8,<3.9
> ```

The new version of sil-machine requires python>=3.8.1

**Review by mshannon-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/524)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @isaac091)

___
*[`environment.yml` line 6 at r1](https://reviewable.io/reviews/sillsdev/silnlp/524#-O768xcF80EgYlmkhE6M:-O76OKTZ5q-C-uVd-ONf:b-376vyb) ([raw file](https://github.com/sillsdev/silnlp/blob/1866015f1725d81d050ace5cb18c2efaa39d14d2/environment.yml#L6)):*
<details><summary><i>Previously, isaac091 (Isaac Schifferer) wrote…</i></summary><blockquote>

The new version of sil-machine requires python>=3.8.1
</blockquote></details>

Done. Good catch.

**Review by isaac091 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/524#-:-O76Q9m0EO2xXLwgX8Hx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Pull request merged**
