### PR TITLE
Remove OpenNMT and Tensorflow, Update to Python 3.10

### PR DESCRIPTION
**Pull request by TaperChipmunk32**
-Removed OpenNMT and Tensorflow dependency
-Updated from Python 3.8 to Python 3.10
-Updated from Ubuntu 20.04 to Ubuntu 22.04
-Updated Transformers to >=4.38.0,<4.46

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583)

### CODE REVIEW

**Review by ddaspit — COMMENTED** [review]
@Enkidu93 Will removing the WER scorer mess up Clowder or the onboarding app in any way?

> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OAxTcXQ12Yf49_XkMuy:b-x6llqf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Comment by Enkidu93** [comment]
> @Enkidu93 Will removing the WER scorer mess up Clowder or the onboarding app in any way?
> 
> > Reviewed 29 of 29 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OAxTcXQ12Yf49_XkMuy:b-x6llqf)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

No, it should be fine.

**Review by ddaspit — COMMENTED** [review]
@TaperChipmunk32 Can you remind me why we can't upgrade to Transformers 4.46? From #521, it sounds like 4.46 supports SDPA for NLLB.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OAyU3Bv6hohyDaCuB45:be1fyei)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @mshannon-sil)

**Comment by TaperChipmunk32** [comment]
> @TaperChipmunk32 Can you remind me why we can't upgrade to Transformers 4.46? From #521, it sounds like 4.46 supports SDPA for NLLB.
> 
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OAyU3Bv6hohyDaCuB45:be1fyei)_ status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @mshannon-sil)

In this [PR](https://github.com/huggingface/transformers/pull/33887/files) for transformers 4.46.0, they deprecated the parameter "tokenizer" for Trainer, which was used in machine.py several times. I'm looking into it for silnlp and that argument may not be used in this repo.

Also, "processing_class" replaced that parameter in an earlier version, so I can look into when that was added to see what versions we could support using that parameter instead.

**Review by ddaspit — COMMENTED** [review]
@isaac091 Will SDPA be enabled by default once we start using Transformers 4.46? Or do we have to explicitly enable it?

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OB2G5bT8plGIP4F0lEz:b-scuabx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Comment by isaac091** [comment]
It should be the default

**Review by mshannon-sil — APPROVED** [review]
:lgtm:

> Reviewed 27 of 29 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OB2XdeE641zSoP7erk6:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TaperChipmunk32)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583)* status: all files reviewed, 1 unresolved discussion (waiting on @TaperChipmunk32)

___
*[`silnlp/nmt/hugging_face_config.py` line 778 at r6](https://reviewable.io/reviews/sillsdev/silnlp/583#-OB75tIQ0xWBSl-jiRQs:-OB75tIQ0xWBSl-jiRQt:b-wtfz1b) ([raw file](https://github.com/sillsdev/silnlp/blob/484dabeb074238e7b43fb85fc267530341fcaf1d/silnlp/nmt/hugging_face_config.py#L778)):*
> ```Python
>             id2label={},
>             num_labels=0,
>             attn_implementation="eager",
> ```

Can you set `attn_implementation` on the config? In the documentation, they set it on `PreTrainedModel.from_pretrained`.

**Comment by TaperChipmunk32** [comment]
> > Reviewed 1 of 1 files at r6, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583)_ status: all files reviewed, 1 unresolved discussion (waiting on @TaperChipmunk32)
> 
> _[`silnlp/nmt/hugging_face_config.py` line 778 at r6](https://reviewable.io/reviews/sillsdev/silnlp/583#-OB75tIQ0xWBSl-jiRQs:-OB75tIQ0xWBSl-jiRQt:b-wtfz1b) ([raw file](https://github.com/sillsdev/silnlp/blob/484dabeb074238e7b43fb85fc267530341fcaf1d/silnlp/nmt/hugging_face_config.py#L778)):_
> 
> > ```python
> >             id2label={},
> >             num_labels=0,
> >             attn_implementation="eager",
> > ```
> 
> Can you set `attn_implementation` on the config? In the documentation, they set it on `PreTrainedModel.from_pretrained`.

Thank you for catching this, I meant to put it in AutoModelForSeq2SeqLM.from_pretrained and not the config. It may be valid in AutoConfig, but I am not sure. I've moved it to match the documentation.

**Review by ddaspit — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OB7M12o9J6EqGM2y5Hc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mshannon-sil)

**Review by mshannon-sil — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583#-:-OB7PRLB5A5Vmqr9Zjn7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TaperChipmunk32)

**Review by ddaspit — COMMENTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/silnlp/583)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @TaperChipmunk32)

**Pull request merged**
